apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-app
    labels:
        app: my-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: my-app
    template:
        metadata:
            labels:
                app: my-app
        spec:
            containers:
                - name: my-app
                  image: teerut26/polstory-go:latest
                  ports:
                      - containerPort: 3000
                  env:
                      - name: GOOGLE_MAPS_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: polstory-secret
                                key: GOOGLE_MAPS_API_KEY

#kubectl create secret generic polstory-secret --from-literal=GOOGLE_MAPS_API_KEY=value
