apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-app
    labels:
        app: my-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: my-app
    template:
        metadata:
            labels:
                app: my-app
        spec:
            containers:
                - name: my-app
                  image: teerut26/polstory-go:latest
                  ports:
                      - containerPort: 3000
                  envFrom:
                      - configMapRef:
                            name: polstory-config
#kubectl create configmap polstory-config --from-env-file=.env
