apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  annotations:
    trafix.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: trafix
  rules:
    - host: polstory-ndis.teerut.com  # Your actual domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-app-service
                port:
                  number: 3000