apiVersion: v1
kind: Service
metadata:
    name: test-k8s-service
spec:
    selector:
        app: test-k8s
    ports:
        - protocol: TCP
          port: 3010 # port on which the service is exposed
          targetPort: 3000 # port on which the container is running
        # - protocol: TCP
        #   port: 3011
        #   targetPort: 80
    type: LoadBalancer
